name: Release mibypass

on:
  push:
    paths:
      - MiBypassTool.py
  pull_request:
    paths:
      - MiBypassTool.py
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload Release
        run: |
          gh release upload mibypass ./MiBypassTool.py --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}