name: Release mibypass

on:
  workflow_dispatch:

env:
  VERSION: mibypass

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload Release
        run: |
          gh release upload ${{ env.VERSION }} ./MibypassTool.py --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.MIBYPASSTOOL }}