name: Release MibypassTool

on:
  workflow_dispatch:

env:
  VERSION: mibypass

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check GitHub CLI version
        run: gh --version

      - name: List files
        run: ls -al

      - name: Upload Release
        run: |
          gh release upload ${{ env.VERSION }} ./MiBypassTool.py --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.MIBYPASSTOOL }}